### ISSUE TITLE
Cannot fork empty repo

### ISSUE THREAD

**Issue by sea-bass** [ros-wg-delib/roscon24-workshop#1]
Hi @ct2034 -- I just made a first branch for a PR containing Docker setup and formatting, but I can't directly push to this repo, and GitHub does not allow forking empty repos.

Could you either add us to this repo as contributors, or initialize the repo so we can submit PRs from our forks?

Thanks!

**Comment by ct2034** [comment]
You should all be maintainers now

**Comment by sea-bass** [comment]
Thanks!

One more thing: There was also no default branch set on this repo, so when I pushed my feature branch it became the default... I made a `main` branch, but don't have the admin power to set that to the default.
