### ISSUE TITLE
Should we include PDDLStream in the Docker image?

### ISSUE THREAD

**Issue by sea-bass** [ros-wg-delib/roscon24-workshop#46]
So, PyRoboSim actually also includes its own task + motion planning solution through PDDLStream, as documented in https://pyrobosim.readthedocs.io/en/latest/usage/tamp.html

It should be easy enough to have this also be part of the Docker image in case we want to demo it, but it will take a few more minutes to build the image because the FastDownward solver needs to be compiled.

Do people think it's worthwhile to keep around in our back pocket?

**Comment by ct2034** [comment]
I agree with @matthias-mayr. I don't think it's adding anything. But if you think about the life of the repo after the workshop, I would like it to be a collection of existing deliberation solutions. Maybe we could add it then with some examples.

**Comment by sea-bass** [comment]
SGTM -- thanks, guys!
